version: '3.8'
services:
  zentry-central:
    build: .
    container_name: zentry-central
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
